### ISSUE TITLE
Shared Memory Sample

### ISSUE THREAD

**Issue by KodrAus** [KodrAus/old-csharp-rust#1]
# TODO

- [ ] Thread safe memory pool
- [x] Rust FFI layer
- [x] .NET FFI layer
- [x] .NET API for interacting with memory through `Span<byte>`
- [x] Rust API for copying memory pool to owned `Vec<u8>`
- [ ] Rust `hyper` server using .NET request handlers

# Notes

Use `Span<byte>` from CoreFX Lab to share buffers with Rust. I'm thinking I'll start by allocating the buffers in Rust rather than .NET so they don't need to be pinned.

With a `Span`, we should be able to read and write the block of memory efficiently. On the Rust side, we can simply read it as a `&[u8]` . An API something like:

```rust
// Trait for types that represent a contiguous block of memory that can safely be written to externally.
unsafe trait Block {
    fn as_ptr(&self) -> BlockPtr;
    fn as_slice(&self) -> &[u8];
}

type BlockPtr = (usize, *const u8);

type Block1024 = [u8; 1024];
type Block4096 = [u8; 4096];

unsafe impl Block for Block1024 {
    fn as_ptr(&self) -> BlockPtr {
        (1024, self as *const u8)
    }
    
    fn as_slice(&self) -> &[u8] {
        self
    }
}
unsafe impl Block for Block4096 {
    fn as_ptr(&self) -> BlockPtr {
        (4096, self as *const u8)
    }
    
    fn as_slice(&self) -> &[u8] {
        self
    }
}

struct Slab<T> {
    blocks: Vec<Slot<T>>
}

impl<T: Block> Slab<T> {
    fn set_used(&mut self, idx: usize, used: usize) {
        if let Some(slot) = self.blocks.get_mut(idx) {
            slot.used = Some(used);
        }
    }
}

struct Slot<T> {
    used: Option<usize>,
    inner: T,
}

fn main() {
    let slab = Slab::<Block1024> {
        blocks: vec![]
    };
    
    // Send to .NET
    let ptr = slab.blocks.get(0).map(|b| b.inner.as_ptr());
    
    // Read the result
    let slice = slab.blocks.get(0).map(|b| {
        match b.used {
            Some(used) => &b.inner.as_slice()[..used],
            None => panic!("attempted to read from block without used len")
        }
    });
}
```

Where `Slab` is from the `slab` crate. On the .NET end:

```csharp
class Native
{
    Span<byte> LeaseBlock()
    {
        var block = lease_block();
        return new Span<byte>(block.ptr, block.capacity);
    }
}

var block = Native.LeaseBlock();
```

Then the standard safety around returning leased blocks etc.

**Comment by KodrAus** [comment]
Figuring out how to buffer data in and out of requests is going to be subtle with `tokio_proto`s `Chunk`. If we stream them through one chunk at a time then there's a cost in marshalling and boxing values. If we push them into a buffer then there's extra memory needed.

I'll have a play with it and see what can be done.

See:

- http://jakegoulding.com/rust-ffi-omnibus/
- https://github.com/hyperium/hyper/blob/master/src/http/chunk.rs#L66-L76
- https://github.com/hyperium/hyper/blob/master/src/http/body.rs#L33-L35
- https://github.com/alexcrichton/futures-rs/blob/master/src/poll.rs#L20-L30
- https://github.com/dotnet/corefxlab/blob/master/docs/specs/pipelines-io.md

**Comment by KodrAus** [comment]
Maybe the `Chunk`s can be written to a `Vec` and then returned to the caller as a pointer and length plus a `bool` to say whether there's more data. Whatever solution it is needs to be safe but efficient since the majority of requests will have a body to parse.

**Comment by KodrAus** [comment]
It's also important that raw pointers are _never_ exposed to the client API. They should only exist in the FFI code on either side.

**Comment by KodrAus** [comment]
This should start with the simplest solution:

- Read the request body into an owned `Vec<u8>`
- Pass a pointer to that `Vec` to the request in a `SafeHandle`
- On `Dispose`, the handle frees the request body
- Allocate a 4k buffer for writing response chunks to
- Write memory to the buffer then call `flush`, that will build a `Vec` from it and send as part of the response body
- Repeat writing chunks until the response is complete

Figure out request metadata like path and headers later

**Comment by KodrAus** [comment]
From an [SO question](http://stackoverflow.com/questions/39224904/how-to-expose-a-rust-vect-to-ffi):

```rust
use std::mem;

let mut boxed_slice: Box<[T]> = vector.into_boxed_slice();

let array: *mut T = boxed_slice.as_mut_ptr();
let array_len: usize = boxed_slice.len();

// Prevent the slice from being destroyed (Leak the memory).
mem::forget(boxed_slice);
```

> NOTE: We're better off getting the length and capacity from the `vec` before turning it into a boxed slice, so it can be turned back into a `Vec` later.

Another example from the [docs](https://doc.rust-lang.org/std/vec/struct.Vec.html#examples-3) that we can use to deconstruct and reconstruct vectors. I'm not sure whether it's ok to go and manually adjust the length parameter after writing your own elements though.

Seems ok, since that's what `vec` [does internally](https://doc.rust-lang.org/src/collections/up/src/libcollections/vec.rs.html#959-962).

**Comment by KodrAus** [comment]
There's a simple example for allocating a Rust `Vec`, and writing to it from .NET with a `Span`. I'll try figure out some decent debugging support for the native code.

**Comment by KodrAus** [comment]
Change the sample to write the bytes it can before resizing and only balk if it doesn't progress. Rather than not allocating until there's enough space.

I think a write method that attempts to write what it can, then requests more space, breaking if it can't write any more bytes after the request should cover the following strategies:

- Get an exact size buffer to write the input into
- Get a new block to write the input into and link it to the old block
- Flush the current contents and overwrite the original buffer

**Comment by KodrAus** [comment]
Before any of this though, the Rust project should be turned into an msbuild `proj` that runs `cargo` and treats the native object as the output. So it should be copied on each build instead of manually.

**Comment by KodrAus** [comment]
msbuild for Rust projects cross platform... Not a thing :( So I've just added a build script. I'll probably redo it in Rust so it's cross platform instead of random shell-ness.

The build will work as follows:

- Invoke `cargo test` on native
- Copy output artifacts to dotnet dir
- run `dotnet build`

Maybe could also support some basic args parsing for `--run` and `--release` or something.

**Comment by KodrAus** [comment]
There's a simple working build tool now. I'm pretty happy with it actually. There's plenty of room for new features.

I'll try convert the params to work off borrowed data, and implement support for watching using something like [this](https://github.com/passcod/notify/blob/master/README.md).

Then I'll just be prepared to revisit assumptions I've made about project structure down the line.

**Comment by KodrAus** [comment]
There are a couple of interfaces we should look at so .NET has a standard interface for controlling the Rust memory:

- `IOutput`
- `ISequence<Memory<byte>>`

**Comment by KodrAus** [comment]
Right now I've got a hard split between readers and writers where you can either do one action or the other. This saves sanity checks on each read or write, since a typical use pattern involves writing some data and then switching to a reader to read or vice-versa.

It still needs some kind of ref counting to make sure you can't convert a reader to a writer while there are active references. An alternative is to prevent conversion from reader to writer.

**Comment by KodrAus** [comment]
As far as the usecase for request/response buffers goes, we can move forward with the resizable buffer that's there. It won't be efficient but is a good start for iterating.
